### ISSUE TITLE
[Question] how to increase table width?

### ISSUE THREAD

**Issue by dhruvinsh** [marc0l92/obsidian-jira-issue#128]
I am using minimal theme (but on default theme as well) how can I increase the width of the table to full view?

**Comment by dhruvinsh** [comment]
Found it,
```css
.jira-table-fix { 
    .cm-content {
        div {
            width: unset !important;
        }
    }
    .table {
        width: 100% !important;
    }
}
```

Use frontmatter property with `cssclasses` set to `jira-table-fix`
